apiVersion: v1
kind: ConfigMap
metadata:
  name: cassandra-configmap
data:
  keyspace-name: booking_system
  contact-points: {{ .Release.Name }}-cassandra:{{ .Values.cassandra.service.ports.cql }}
  cluster-name: {{ .Values.cassandra.cluster.name }}
  datacenter: {{ .Values.cassandra.cluster.datacenter }}
  rack: {{ .Values.cassandra.cluster.rack }}