apiVersion: v1
kind: Service
metadata:
  name: cassandra
  namespace: booking-system
spec:
  selector:
    app: cassandra
  ports:
    - name: cql
      port: 9042
      targetPort: cql
---
apiVersion: v1
kind: Service
metadata:
  name: cassandra-headless
  namespace: booking-system
spec:
  selector:
    app: cassandra
  clusterIP: None
  ports:
    - name: intra
      port: 7000
      targetPort: intra
    - name: tls
      port: 7001
      targetPort: tls
    - name: jmx
      port: 7199
      targetPort: jmx
    - name: cql
      port: 9042
      targetPort: cql
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cassandra-configmap
  namespace: booking-system
data:
  keyspace-name: booking_system
  contact-points: cassandra:9042
  datacenter: DC1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra
  namespace: booking-system
spec:
  selector:
    matchLabels:
      app: cassandra
  serviceName: cassandra-headless
  replicas: 1
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
        - name: cassandra
          image: cassandra:5.0.6
          resources:
            requests:
              memory: 2Gi
              cpu: 1
            limits:
              memory: 3Gi
              cpu: 2
          env:
            - name: CASSANDRA_CLUSTER_NAME
              value: booking-system
            - name: CASSANDRA_DC
              valueFrom:
                configMapKeyRef:
                  name: cassandra-configmap
                  key: datacenter
            - name: CASSANDRA_RACK
              value: RACK1
            - name: CASSANDRA_SEEDS
              value: cassandra-0.cassandra-headless.booking-system.svc.cluster.local
            - name: CASSANDRA_NUM_TOKENS
              value: "256"
            - name: CASSANDRA_ENDPOINT_SNITCH
              value: GossipingPropertyFileSnitch
            - name: MAX_HEAP_SIZE
              value: 2G
            - name: HEAP_NEWSIZE
              value: 1G
          ports:
            - name: intra
              containerPort: 7000
            - name: tls
              containerPort: 7001
            - name: jmx
              containerPort: 7199
            - name: cql
              containerPort: 9042
          volumeMounts:
            - name: cassandra
              mountPath: /var/lib/cassandra
  volumeClaimTemplates:
    - metadata:
        name: cassandra
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: local-storage
        selector:
          matchLabels:
            app: cassandra
        resources:
          requests:
            storage: 1Gi