apiVersion: v1
kind: Service
metadata:
  name: query-service
spec:
  selector:
    app: query-service
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: query-service-configmap
data:
  query-service-address: query-service:50051
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-service
spec:
  selector:
    matchLabels:
      app: query-service
  replicas: 1
  template:
    metadata:
      labels:
        app: query-service
    spec:
      containers:
        - name: query-service
          image: booking-system-query-service:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: BOOKING_SYSTEM_CASSANDRA_CONTACT_POINTS
              valueFrom:
                configMapKeyRef:
                  name: cassandra-configmap
                  key: contact-points
            - name: BOOKING_SYSTEM_CASSANDRA_KEYSPACE_NAME
              valueFrom:
                configMapKeyRef:
                  name: cassandra-configmap
                  key: keyspace-name
            - name: BOOKING_SYSTEM_CASSANDRA_DATACENTER
              valueFrom:
                configMapKeyRef:
                  name: cassandra-configmap
                  key: datacenter
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: otel-collector-configmap
                  key: endpoint
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: grpc
            - name: OTEL_SERVICE_NAME
              value: query-service
            - name: OTEL_TRACES_EXPORTER
              value: otlp
            - name: OTEL_METRICS_EXPORTER
              value: otlp
            - name: OTEL_LOGS_EXPORTER
              value: otlp
            - name: OTEL_INSTRUMENTATION_LOGBACK_APPENDER_EXPERIMENTAL_CAPTURE_MDC_ATTRIBUTES
              value: "*"
            - name: OTEL_INSTRUMENTATION_LOGBACK_APPENDER_EXPERIMENTAL_CAPTURE_KEY_VALUE_PAIR_ATTRIBUTES
              value: "true"
            - name: OTEL_INSTRUMENTATION_LOGBACK_APPENDER_EXPERIMENTAL_CAPTURE_LOGGER_CONTEXT_ATTRIBUTES
              value: "true"
          ports:
            - containerPort: 50051
