apiVersion: apps/v1
kind: Deployment
metadata:
  name: command-service
spec:
  selector:
    matchLabels:
      app: command-service
  replicas: 1
  template:
    metadata:
      labels:
        app: command-service
    spec:
      containers:
        - name: command-service
          image: booking-system-command-service:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: BOOKING_SYSTEM_CASSANDRA_CONTACT_POINTS
              valueFrom:
                configMapKeyRef:
                  name: cassandra-configmap
                  key: contact-points
            - name: BOOKING_SYSTEM_CASSANDRA_KEYSPACE_NAME
              valueFrom:
                configMapKeyRef:
                  name: cassandra-configmap
                  key: keyspace-name
            - name: BOOKING_SYSTEM_CASSANDRA_DATACENTER
              valueFrom:
                configMapKeyRef:
                  name: cassandra-configmap
                  key: datacenter
            - name: BOOKING_SYSTEM_KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: kafka-configmap
                  key: bootstrap-servers
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: BOOKING_SYSTEM_KAFKA_COMMAND_SERVICE_CLIENT_ID
              value: $(POD_NAME)
            - name: BOOKING_SYSTEM_KAFKA_COMMAND_SERVICE_GROUP_ID
              value: command-consumers
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: otel-collector-configmap
                  key: endpoint
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: grpc
            - name: OTEL_SERVICE_NAME
              value: $(POD_NAME)
            - name: OTEL_TRACES_EXPORTER
              value: otlp
            - name: OTEL_METRICS_EXPORTER
              value: otlp
            - name: OTEL_LOGS_EXPORTER
              value: otlp
            - name: OTEL_INSTRUMENTATION_LOGBACK_APPENDER_EXPERIMENTAL_CAPTURE_MDC_ATTRIBUTES
              value: "*"
            - name: OTEL_INSTRUMENTATION_LOGBACK_APPENDER_EXPERIMENTAL_CAPTURE_KEY_VALUE_PAIR_ATTRIBUTES
              value: "true"
            - name: OTEL_INSTRUMENTATION_LOGBACK_APPENDER_EXPERIMENTAL_CAPTURE_LOGGER_CONTEXT_ATTRIBUTES
              value: "true"