opentelemetry-collector:
  mode: deployment
  image:
    repository: otel/opentelemetry-collector-contrib
    tag: 0.143.1
  config:
    exporters:
      otlp:
        endpoint: booking-system-tempo:4317
        tls:
          insecure: true
      otlphttp:
        endpoint: http://booking-system-loki:3100/otlp
      prometheus:
        endpoint: ${env:MY_POD_IP}:9090
    service:
      pipelines:
        traces:
          exporters:
            - otlp
        metrics:
          exporters:
            - prometheus
        logs:
          exporters:
            - otlphttp
  ports:
    metrics:
      enabled: true
      containerPort: 9090
      servicePort: 9090

prometheus:
  server:
    image:
      repository: prom/prometheus
      tag: v3.9.1
    service:
      servicePort: 9090
    persistentVolume:
      size: 1G
      storageClass: local-storage
      selector:
        matchLabels:
          app: prometheus
    extraArgs:
      web.enable-remote-write-receiver: null
      enable-feature: exemplar-storage,native-histograms
    global:
      scrape_interval: 1s
      scrape_timeout: 1s
  scrapeConfigs:
    otel-collector:
      static_configs:
        - targets:
            - booking-system-opentelemetry-collector:9090
    prometheus:
      enabled: false
    kubernetes-api-servers:
      enabled: false
    kubernetes-nodes:
      enabled: false
    kubernetes-nodes-cadvisor:
      enabled: false
    kubernetes-service-endpoints:
      enabled: false
    kubernetes-service-endpoints-slow:
      enabled: false
    prometheus-pushgateway:
      enabled: false
    kubernetes-services:
      enabled: false
    kubernetes-pods:
      enabled: false
    kubernetes-pods-slow:
      enabled: false
  configmapReload:
    prometheus:
      enabled: false
  alertmanager:
    enabled: false
  prometheus-node-exporter:
    enabled: false
  prometheus-pushgateway:
    enabled: false
  kube-state-metrics:
    enabled: false

loki:
  deploymentMode: SingleBinary
  loki:
    image:
      tag: 3.6.3
    auth_enabled: false
    commonConfig:
      replication_factor: 1
    schemaConfig:
      configs:
        - from: 2024-04-01
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            period: 24h
    storage:
      type: filesystem
  test:
    enabled: false
  singleBinary:
    replicas: 1
    persistence:
      enabled: true
      storageClass: local-storage
      size: 1Gi
      selector:
        matchLabels:
          app: loki
  backend:
    replicas: 0
  read:
    replicas: 0
  write:
    replicas: 0
  ingester:
    replicas: 0
  querier:
    replicas: 0
  queryFrontend:
    replicas: 0
  queryScheduler:
    replicas: 0
  distributor:
    replicas: 0
  compactor:
    replicas: 0
  indexGateway:
    replicas: 0
  bloomGateway:
    replicas: 0
  chunksCache:
    enabled: false
  gateway:
    enabled: false
  resultsCache:
    enabled: false
  lokiCanary:
    enabled: false

tempo:
  tempo:
    tag: 2.9.0
    metricsGenerator:
      enabled: true
      remoteWriteUrl: http://booking-system-prometheus-server:9090/api/v1/write
      storage:
        path: /var/tempo/metrics
      traces_storage:
        path: /var/tempo/wal
    overrides:
      defaults:
        metrics_generator:
          processors:
            - local-blocks

  persistence:
    enabled: true
    size: 2G
    storageClassName: local-storage

grafana:
  image:
    tag: 12.3.1
  adminPassword: admin
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Loki
          type: loki
          access: proxy
          url: http://booking-system-loki:3100
          isDefault: false

        - name: Prometheus
          type: prometheus
          access: proxy
          url: http://booking-system-prometheus-server:9090
          isDefault: false

        - name: Tempo
          type: tempo
          access: proxy
          url: http://booking-system-tempo:3200
          isDefault: true
          uid: tempo

localPVs:
  - name: cassandra-0
    app: cassandra
    size: 1Gi
    node: minikube

  - name: prometheus-0
    app: prometheus
    size: 1Gi
    node: minikube

  - name: tempo-0
    app: tempo
    size: 2Gi
    node: minikube

  - name: loki-0
    app: loki
    size: 1Gi
    node: minikube

  - name: pv-0
    size: 1Gi
    node: minikube

  - name: pv-1
    size: 1Gi
    node: minikube

  - name: pv-2
    size: 1Gi
    node: minikube

  - name: pv-3
    size: 1Gi
    node: minikube

  - name: pv-4
    size: 1Gi
    node: minikube