localPVs:
  - name: cassandra-0
    app: cassandra
    size: 1Gi
    node: minikube

  - name: prometheus-0
    app: prometheus
    size: 1Gi
    node: minikube

  - name: tempo-0
    app: tempo
    size: 1Gi
    node: minikube

  - name: loki-0
    app: loki
    size: 1Gi
    node: minikube

  - name: alloy-0
    app: alloy
    size: 1Gi
    node: minikube

  - name: pv-0
    size: 1Gi
    node: minikube

  - name: pv-1
    size: 1Gi
    node: minikube

  - name: pv-2
    size: 1Gi
    node: minikube

  - name: pv-3
    size: 1Gi
    node: minikube

  - name: pv-4
    size: 1Gi
    node: minikube